import type { CategoryId, Product } from "@/lib/types";

/**
 * كتالوج المنتجات.
 * الأسعار بالجنيه المصري: retailPrice سعر القطعة للأفراد،
 * wholesalePrice سعر القطعة للتجار عند الالتزام بالحد الأدنى للكمية.
 */
export const products: Product[] = [
  {
    id: "p-1001",
    slug: "sayara-sibaq-tahakkum",
    name: "سيارة سباق بجهاز تحكم عن بعد",
    shortDescription: "سيارة سباق مقاس 1:18 بجهاز تحكم لاسلكي وبطارية قابلة للشحن.",
    description:
      "سيارة سباق بلاستيك مقوى مقاس 1:18 تعمل بجهاز تحكم لاسلكي على تردد 2.4 جيجاهرتز، مزودة ببطارية قابلة للشحن وكابل شحن. تصلح لمحلات الألعاب ومنافذ التوزيع، وتُورَّد داخل علبة عرض مطبوعة.",
    categoryId: "vehicles",
    retailPrice: 385,
    wholesalePrice: 268,
    images: [
      { src: "/products/vehicles-01-a.svg", alt: "سيارة سباق بجهاز تحكم عن بعد — عرض جانبي" },
      { src: "/products/vehicles-01-b.svg", alt: "سيارة سباق بجهاز تحكم عن بعد — علبة العرض" },
    ],
    sku: "OMR-VH-1001",
    packaging: {
      unitsPerCarton: 12,
      minWholesaleUnits: 12,
      cartonWeightKg: 9.5,
      cartonDimensions: "60 × 40 × 45 سم",
    },
    ageRange: "من 5 إلى 12 سنة",
    material: "بلاستيك ABS مقوى",
    origin: "مستورد",
    colors: ["أحمر", "أزرق", "أسود"],
    inStock: true,
    featured: true,
    badges: ["يشمل بطارية", "علبة عرض"],
  },
  {
    id: "p-1002",
    slug: "shahina-naql-kabira",
    name: "شاحنة نقل كبيرة بالدفع اليدوي",
    shortDescription: "شاحنة بلاستيك متينة بصندوق متحرك، مناسبة للاستخدام الداخلي والخارجي.",
    description:
      "شاحنة نقل بطول 42 سم تعمل بالدفع اليدوي بدون بطاريات، بصندوق خلفي متحرك وعجلات مطاطية صامتة. مناسبة للعرض المفتوح داخل المحلات نظراً لمتانتها وقلة نسبة الكسر أثناء التداول.",
    categoryId: "vehicles",
    retailPrice: 240,
    wholesalePrice: 162,
    images: [
      { src: "/products/vehicles-02-a.svg", alt: "شاحنة نقل كبيرة بالدفع اليدوي" },
      { src: "/products/vehicles-02-b.svg", alt: "شاحنة نقل — تفاصيل الصندوق الخلفي" },
    ],
    sku: "OMR-VH-1002",
    packaging: {
      unitsPerCarton: 8,
      minWholesaleUnits: 8,
      cartonWeightKg: 11,
      cartonDimensions: "70 × 45 × 50 سم",
    },
    ageRange: "من 3 إلى 8 سنوات",
    material: "بلاستيك عالي الكثافة",
    origin: "صناعة محلية",
    colors: ["أصفر", "برتقالي", "أخضر"],
    inStock: true,
    featured: false,
    badges: ["بدون بطاريات", "متانة عالية"],
  },
  {
    id: "p-1003",
    slug: "majmoaa-sayarat-maadan-6",
    name: "طقم 6 سيارات معدنية",
    shortDescription: "ستة موديلات معدنية مقاس 1:64 داخل علبة كرتون مطبوعة.",
    description:
      "طقم مكوّن من ست سيارات معدنية مقاس 1:64 بموديلات متنوعة وعجلات حرة الحركة. يُورَّد في علبة كرتون مطبوعة تصلح للعرض المباشر على الرف، وهو من الأصناف سريعة الدوران في منافذ التجزئة.",
    categoryId: "vehicles",
    retailPrice: 175,
    wholesalePrice: 112,
    images: [
      { src: "/products/vehicles-03-a.svg", alt: "طقم 6 سيارات معدنية" },
      { src: "/products/vehicles-03-b.svg", alt: "طقم سيارات معدنية داخل علبة العرض" },
    ],
    sku: "OMR-VH-1003",
    packaging: {
      unitsPerCarton: 24,
      minWholesaleUnits: 24,
      cartonWeightKg: 12,
      cartonDimensions: "55 × 38 × 40 سم",
    },
    ageRange: "من 4 سنوات فأكثر",
    material: "معدن مصبوب وبلاستيك",
    origin: "مستورد",
    colors: ["ألوان متنوعة"],
    inStock: true,
    featured: true,
    badges: ["سريع الدوران", "علبة عرض"],
  },
  {
    id: "p-1004",
    slug: "darraja-thulathiya-atfal",
    name: "دراجة أطفال ثلاثية العجلات",
    shortDescription: "دراجة بهيكل معدني ومقعد مبطّن ومسند خلفي للتوجيه.",
    description:
      "دراجة ثلاثية العجلات بهيكل معدني مطلي ومقعد مبطّن قابل للتعديل، مزودة بمسند خلفي يسمح لولي الأمر بالتوجيه وسلة أمامية. تُورَّد مفكوكة داخل كرتونة مع كتيب التركيب.",
    categoryId: "vehicles",
    retailPrice: 1150,
    wholesalePrice: 845,
    images: [
      { src: "/products/vehicles-04-a.svg", alt: "دراجة أطفال ثلاثية العجلات" },
      { src: "/products/vehicles-04-b.svg", alt: "دراجة أطفال — المقعد والمسند الخلفي" },
    ],
    sku: "OMR-VH-1004",
    packaging: {
      unitsPerCarton: 2,
      minWholesaleUnits: 4,
      cartonWeightKg: 14,
      cartonDimensions: "75 × 40 × 55 سم",
    },
    ageRange: "من سنتين إلى 5 سنوات",
    material: "هيكل معدني وعجلات إيفا",
    origin: "مستورد",
    colors: ["وردي", "أزرق", "رمادي"],
    inStock: true,
    featured: false,
    badges: ["هيكل معدني", "تُورَّد مفكوكة"],
  },
  {
    id: "p-2001",
    slug: "aroosa-kalasikiya-45",
    name: "عروسة كلاسيكية 45 سم",
    shortDescription: "عروسة بمفاصل متحركة وشعر قابل للتصفيف مع طقم ملابس.",
    description:
      "عروسة بارتفاع 45 سم بمفاصل متحركة وشعر صناعي قابل للتصفيف، تُورَّد بطقم ملابس وحذاء داخل علبة عرض شفافة. من الأصناف الثابتة الطلب طوال العام وتزيد مبيعاتها في مواسم الأعياد.",
    categoryId: "dolls",
    retailPrice: 320,
    wholesalePrice: 215,
    images: [
      { src: "/products/dolls-01-a.svg", alt: "عروسة كلاسيكية 45 سم" },
      { src: "/products/dolls-01-b.svg", alt: "عروسة كلاسيكية — علبة العرض" },
    ],
    sku: "OMR-DL-2001",
    packaging: {
      unitsPerCarton: 16,
      minWholesaleUnits: 16,
      cartonWeightKg: 10,
      cartonDimensions: "62 × 42 × 48 سم",
    },
    ageRange: "من 3 سنوات فأكثر",
    material: "فينيل وقماش",
    origin: "مستورد",
    colors: ["وردي", "أبيض", "بنفسجي"],
    inStock: true,
    featured: true,
    badges: ["طلب ثابت", "علبة شفافة"],
  },
  {
    id: "p-2002",
    slug: "dumya-qutniya-30",
    name: "دمية قطنية 30 سم",
    shortDescription: "دمية محشوة بخامة قطنية آمنة وقابلة للغسل.",
    description:
      "دمية محشوة بارتفاع 30 سم من خامة قطنية ناعمة وحشو بوليستر، بخياطة مزدوجة وعيون مطرزة بدون أجزاء صغيرة قابلة للانفصال. قابلة للغسل اليدوي وتصلح لكل الأعمار.",
    categoryId: "dolls",
    retailPrice: 145,
    wholesalePrice: 92,
    images: [
      { src: "/products/dolls-02-a.svg", alt: "دمية قطنية 30 سم" },
      { src: "/products/dolls-02-b.svg", alt: "دمية قطنية — تفاصيل الخياطة" },
    ],
    sku: "OMR-DL-2002",
    packaging: {
      unitsPerCarton: 30,
      minWholesaleUnits: 30,
      cartonWeightKg: 8,
      cartonDimensions: "80 × 50 × 55 سم",
    },
    ageRange: "من سنة فأكثر",
    material: "قماش قطني وحشو بوليستر",
    origin: "صناعة محلية",
    colors: ["بيج", "بني", "وردي"],
    inStock: true,
    featured: false,
    badges: ["عيون مطرزة", "قابلة للغسل"],
  },
  {
    id: "p-2003",
    slug: "mujassamat-hayawanat-12",
    name: "مجموعة مجسمات حيوانات (12 قطعة)",
    shortDescription: "اثنا عشر مجسماً بتفاصيل واقعية داخل كيس عرض بسحّاب.",
    description:
      "مجموعة من 12 مجسم حيوان بأحجام تتراوح بين 6 و10 سم، مصنوعة من بلاستيك PVC مصمت بألوان ثابتة. تُورَّد داخل كيس بسحّاب مع بطاقة تعريفية، وتُستخدم كذلك كوسيلة إيضاح في الحضانات.",
    categoryId: "dolls",
    retailPrice: 190,
    wholesalePrice: 124,
    images: [
      { src: "/products/dolls-03-a.svg", alt: "مجموعة مجسمات حيوانات 12 قطعة" },
      { src: "/products/dolls-03-b.svg", alt: "مجسمات حيوانات — كيس العرض" },
    ],
    sku: "OMR-DL-2003",
    packaging: {
      unitsPerCarton: 24,
      minWholesaleUnits: 24,
      cartonWeightKg: 9,
      cartonDimensions: "58 × 40 × 42 سم",
    },
    ageRange: "من 3 سنوات فأكثر",
    material: "بلاستيك PVC مصمت",
    origin: "مستورد",
    colors: ["ألوان طبيعية"],
    inStock: true,
    featured: false,
    badges: ["12 قطعة", "ألوان ثابتة"],
  },
  {
    id: "p-2004",
    slug: "dub-qutni-kabir-60",
    name: "دب قطني كبير 60 سم",
    shortDescription: "دب محشو بارتفاع 60 سم مناسب للهدايا وواجهات العرض.",
    description:
      "دب محشو بارتفاع 60 سم من خامة مخملية ناعمة وحشو مضغوط يحافظ على الشكل. يُستخدم كهدية مناسبات وكذلك في تنسيق واجهات العرض داخل المحلات.",
    categoryId: "dolls",
    retailPrice: 430,
    wholesalePrice: 298,
    images: [
      { src: "/products/dolls-04-a.svg", alt: "دب قطني كبير 60 سم" },
      { src: "/products/dolls-04-b.svg", alt: "دب قطني كبير — عرض جانبي" },
    ],
    sku: "OMR-DL-2004",
    packaging: {
      unitsPerCarton: 10,
      minWholesaleUnits: 10,
      cartonWeightKg: 7.5,
      cartonDimensions: "90 × 60 × 60 سم",
    },
    ageRange: "من 3 سنوات فأكثر",
    material: "قماش مخملي وحشو بوليستر",
    origin: "صناعة محلية",
    colors: ["بني", "بيج", "أبيض"],
    inStock: true,
    featured: true,
    badges: ["مناسب للهدايا", "حشو مضغوط"],
  },
  {
    id: "p-3001",
    slug: "mukaabat-tarkeeb-120",
    name: "مكعبات تركيب 120 قطعة",
    shortDescription: "مكعبات متوافقة القياس بألوان أساسية داخل صندوق بلاستيك.",
    description:
      "صندوق يضم 120 قطعة مكعبات تركيب بمقاسات متوافقة وحواف مصقولة، بألوان أساسية ثابتة. يُورَّد داخل صندوق بلاستيك بغطاء يسهل تخزينه وإعادة عرضه.",
    categoryId: "educational",
    retailPrice: 265,
    wholesalePrice: 178,
    images: [
      { src: "/products/educational-01-a.svg", alt: "مكعبات تركيب 120 قطعة" },
      { src: "/products/educational-01-b.svg", alt: "مكعبات تركيب — صندوق التخزين" },
    ],
    sku: "OMR-ED-3001",
    packaging: {
      unitsPerCarton: 12,
      minWholesaleUnits: 12,
      cartonWeightKg: 13,
      cartonDimensions: "60 × 45 × 48 سم",
    },
    ageRange: "من 3 إلى 10 سنوات",
    material: "بلاستيك ABS",
    origin: "مستورد",
    colors: ["ألوان أساسية"],
    inStock: true,
    featured: true,
    badges: ["120 قطعة", "حواف مصقولة"],
  },
  {
    id: "p-3002",
    slug: "buzzle-khashab-huruf",
    name: "بازل خشبي للحروف العربية",
    shortDescription: "لوحة خشبية بـ 28 حرفاً مع مقابض للإمساك السهل.",
    description:
      "لوحة بازل خشبية تضم الحروف العربية الثمانية والعشرين، كل حرف بمقبض صغير يسهل التقاطه. الخشب مصنفر ومطلي بدهانات مائية آمنة، ويستخدمها كثير من دور الحضانة ضمن أدوات التعليم المبكر.",
    categoryId: "educational",
    retailPrice: 210,
    wholesalePrice: 138,
    images: [
      { src: "/products/educational-02-a.svg", alt: "بازل خشبي للحروف العربية" },
      { src: "/products/educational-02-b.svg", alt: "بازل الحروف — تفاصيل المقابض" },
    ],
    sku: "OMR-ED-3002",
    packaging: {
      unitsPerCarton: 20,
      minWholesaleUnits: 20,
      cartonWeightKg: 15,
      cartonDimensions: "50 × 40 × 45 سم",
    },
    ageRange: "من 3 إلى 7 سنوات",
    material: "خشب MDF ودهانات مائية",
    origin: "صناعة محلية",
    colors: ["ألوان متنوعة"],
    inStock: true,
    featured: false,
    badges: ["دهان مائي", "للحضانات"],
  },
  {
    id: "p-3003",
    slug: "lawha-rasm-magnetic",
    name: "لوحة رسم مغناطيسية",
    shortDescription: "لوحة رسم قابلة للمسح مع قلم وثلاثة أختام.",
    description:
      "لوحة رسم مغناطيسية مقاس 30 × 25 سم بقلم مثبت بخيط وثلاثة أختام أشكال، مع ذراع مسح يعيد اللوحة نظيفة. لا تحتاج بطاريات ولا أقلام استهلاكية، وهي من الأصناف المطلوبة كهدية عملية.",
    categoryId: "educational",
    retailPrice: 155,
    wholesalePrice: 98,
    images: [
      { src: "/products/educational-03-a.svg", alt: "لوحة رسم مغناطيسية" },
      { src: "/products/educational-03-b.svg", alt: "لوحة رسم مغناطيسية — القلم والأختام" },
    ],
    sku: "OMR-ED-3003",
    packaging: {
      unitsPerCarton: 24,
      minWholesaleUnits: 24,
      cartonWeightKg: 11,
      cartonDimensions: "56 × 40 × 44 سم",
    },
    ageRange: "من 3 سنوات فأكثر",
    material: "بلاستيك ومسحوق مغناطيسي",
    origin: "مستورد",
    colors: ["أزرق", "وردي", "أخضر"],
    inStock: true,
    featured: false,
    badges: ["بدون بطاريات", "قابلة للمسح"],
  },
  {
    id: "p-3004",
    slug: "majmoaa-tajarib-ilmiya",
    name: "مجموعة تجارب علمية للمبتدئين",
    shortDescription: "أدوات تجارب آمنة مع دليل مصور بالعربية.",
    description:
      "مجموعة تضم أدوات تجارب بسيطة وآمنة (أنابيب، عدسة، مجهر مبدئي، عينات) مع دليل مصور بالعربية يشرح عشر تجارب. تُورَّد في علبة مقسّمة تحافظ على ترتيب الأدوات.",
    categoryId: "educational",
    retailPrice: 495,
    wholesalePrice: 352,
    images: [
      { src: "/products/educational-04-a.svg", alt: "مجموعة تجارب علمية للمبتدئين" },
      { src: "/products/educational-04-b.svg", alt: "مجموعة تجارب علمية — محتويات العلبة" },
    ],
    sku: "OMR-ED-3004",
    packaging: {
      unitsPerCarton: 10,
      minWholesaleUnits: 10,
      cartonWeightKg: 12,
      cartonDimensions: "58 × 42 × 46 سم",
    },
    ageRange: "من 7 إلى 14 سنة",
    material: "بلاستيك وزجاج آمن",
    origin: "مستورد",
    colors: ["أزرق"],
    inStock: true,
    featured: true,
    badges: ["دليل بالعربية", "10 تجارب"],
  },
  {
    id: "p-4001",
    slug: "balonat-latex-100",
    name: "بالونات لاتكس (عبوة 100 بالون)",
    shortDescription: "بالونات لاتكس مقاس 12 بوصة بألوان متنوعة.",
    description:
      "عبوة تضم 100 بالون لاتكس مقاس 12 بوصة بسماكة موحدة تتحمل النفخ بالهواء أو الهيليوم. الألوان متنوعة داخل العبوة الواحدة، وتُورَّد في أكياس محكمة الغلق تحافظ على مرونة اللاتكس.",
    categoryId: "gifts-balloons",
    retailPrice: 120,
    wholesalePrice: 72,
    images: [
      { src: "/products/gifts-01-a.svg", alt: "بالونات لاتكس عبوة 100 بالون" },
      { src: "/products/gifts-01-b.svg", alt: "بالونات لاتكس — العبوة" },
    ],
    sku: "OMR-GB-4001",
    packaging: {
      unitsPerCarton: 50,
      minWholesaleUnits: 50,
      cartonWeightKg: 14,
      cartonDimensions: "60 × 40 × 40 سم",
    },
    ageRange: "بإشراف بالغ",
    material: "لاتكس طبيعي",
    origin: "مستورد",
    colors: ["ألوان متنوعة"],
    inStock: true,
    featured: true,
    badges: ["100 بالون", "يصلح للهيليوم"],
  },
  {
    id: "p-4002",
    slug: "balonat-foil-arqam",
    name: "بالونات فويل أرقام 40 بوصة",
    shortDescription: "بالون فويل رقمي مقاس 40 بوصة بصمام ذاتي الغلق.",
    description:
      "بالون فويل على شكل رقم مقاس 40 بوصة بصمام ذاتي الغلق يسمح بإعادة النفخ. متوفر بالأرقام من صفر إلى تسعة وبلونين ذهبي وفضي، ويُطلب عادة بكميات موزعة على الأرقام.",
    categoryId: "gifts-balloons",
    retailPrice: 85,
    wholesalePrice: 48,
    images: [
      { src: "/products/gifts-02-a.svg", alt: "بالونات فويل أرقام 40 بوصة" },
      { src: "/products/gifts-02-b.svg", alt: "بالون فويل رقمي — الصمام الذاتي" },
    ],
    sku: "OMR-GB-4002",
    packaging: {
      unitsPerCarton: 100,
      minWholesaleUnits: 50,
      cartonWeightKg: 6,
      cartonDimensions: "55 × 40 × 30 سم",
    },
    ageRange: "بإشراف بالغ",
    material: "فويل ألومنيوم",
    origin: "مستورد",
    colors: ["ذهبي", "فضي"],
    inStock: true,
    featured: false,
    badges: ["صمام ذاتي", "إعادة نفخ"],
  },
  {
    id: "p-4003",
    slug: "taqm-tajheez-hafla",
    name: "طقم تجهيز حفلة متكامل",
    shortDescription: "أطباق وأكواب وشرائط وبالونات لعشرة أشخاص.",
    description:
      "طقم تجهيز حفلة يكفي عشرة أشخاص ويضم أطباقاً وأكواباً ومفارش وشرائط زينة وبالونات بتصميم موحد. يُباع كوحدة واحدة ويقلل على المحل عناء تجميع الأصناف المتفرقة.",
    categoryId: "gifts-balloons",
    retailPrice: 275,
    wholesalePrice: 185,
    images: [
      { src: "/products/gifts-03-a.svg", alt: "طقم تجهيز حفلة متكامل" },
      { src: "/products/gifts-03-b.svg", alt: "طقم تجهيز حفلة — محتويات الطقم" },
    ],
    sku: "OMR-GB-4003",
    packaging: {
      unitsPerCarton: 20,
      minWholesaleUnits: 20,
      cartonWeightKg: 10,
      cartonDimensions: "60 × 45 × 42 سم",
    },
    ageRange: "لجميع الأعمار",
    material: "ورق مقوى وبلاستيك",
    origin: "مستورد",
    colors: ["أزرق", "وردي", "ذهبي"],
    inStock: true,
    featured: false,
    badges: ["يكفي 10 أفراد", "تصميم موحد"],
  },
  {
    id: "p-4004",
    slug: "elab-hadaya-mutanawea",
    name: "علب هدايا بمقاسات متدرجة",
    shortDescription: "ثلاث مقاسات من علب الهدايا المقواة مع شريط ساتان.",
    description:
      "علب هدايا من الكرتون المقوى بثلاثة مقاسات متدرجة وغطاء منفصل وشريط ساتان. مناسبة لمحلات الهدايا ولتغليف المنتجات داخل المعارض، وتُورَّد مسطحة لتوفير مساحة التخزين.",
    categoryId: "gifts-balloons",
    retailPrice: 160,
    wholesalePrice: 104,
    images: [
      { src: "/products/gifts-04-a.svg", alt: "علب هدايا بمقاسات متدرجة" },
      { src: "/products/gifts-04-b.svg", alt: "علب هدايا — شريط الساتان" },
    ],
    sku: "OMR-GB-4004",
    packaging: {
      unitsPerCarton: 30,
      minWholesaleUnits: 30,
      cartonWeightKg: 9,
      cartonDimensions: "62 × 45 × 40 سم",
    },
    ageRange: "لجميع الأعمار",
    material: "كرتون مقوى وساتان",
    origin: "صناعة محلية",
    colors: ["أحمر", "ذهبي", "أبيض"],
    inStock: false,
    featured: false,
    badges: ["3 مقاسات", "تُورَّد مسطحة"],
  },
];

/** خريطة سريعة للوصول إلى المنتج عبر المعرف */
export const productMap: Record<string, Product> = products.reduce(
  (acc, product) => {
    acc[product.id] = product;
    return acc;
  },
  {} as Record<string, Product>,
);

export function getProductById(id: string): Product | undefined {
  return productMap[id];
}

export function getProductsByCategory(categoryId: CategoryId): Product[] {
  return products.filter((product) => product.categoryId === categoryId);
}

/** عدد المنتجات في كل قسم */
export function countByCategory(): Record<CategoryId, number> {
  return products.reduce(
    (acc, product) => {
      acc[product.categoryId] = (acc[product.categoryId] ?? 0) + 1;
      return acc;
    },
    {} as Record<CategoryId, number>,
  );
}
